### ISSUE TITLE
Multiple image bug

### ISSUE THREAD

**Issue by sarbogast** [trentrichardson/UberUploadCropper#3] opened 2013-02-07 11:24 UTC
I'm trying out the example code in the project as is. When I upload the first image, everything is fine. But when I click on "Upload" again, I get 2 modal dialogs like this:

![Capture d e cran 2013-02-07 a 12 16 49](https://f.cloud.github.com/assets/143758/135290/7e1a163e-7118-11e2-9c59-333c5ba0363e.png)

And then when I click done, it's processing forever:

![Capture d e cran 2013-02-07 a 12 17 07](https://f.cloud.github.com/assets/143758/135293/912be8b0-7118-11e2-9033-3de0f9ac0e61.png)

Note that I have exactly the same symptoms with example-basic and example-advanced, I'm using Chrome 24.0.1312.57 and I didn't change anything in the code of the samples.

**Comment by devilmastah** [comment] 2013-02-26 18:19
I can confirm the problem, i have looked into it a bit and it seems that something is wrong with the $.each(imgdata,function(i,obj){ function on line 82 in jquery-uberuploadcropper.js
If someone can fix this please post it :) i cant seem to find it

**Comment by macodev** [comment] 2013-03-13 09:19
The problem isn't imgdata, but jQuery bind command. It is called inside loops and multiple function calls.
Even if the name of the bind is the same, jQuery saves each multiple times in an array (read jQuery bind docs).
I just added a pull request patch that resolve this issue.

**Comment by trentrichardson** [comment] 2013-03-13 12:44
Pull request has been merged, so I am closing this issue.  Thanks to all for your help!

**Closed as completed by trentrichardson** 2013-03-13 12:44 UTC
